ecaps1038/yike-design-dev

.gitignore
src/components/bar.vue
src/yike-design/components/container/YkContainer.vue

这个提交修复了Container元素的滚动条因resize 而没有重新计算高度导致scroll高度错误以及显示错误问题。

fix: container height bug and add height reload

---

demo/src/router/modules/feedback.ts
demo/src/router/modules/general.ts

fix(base): 修改文档的菜单路由指向

---

packages/yike-design-ui/src/components/button/src/button.vue

withDefaults-修复button组件的默认props中type的值未填写

fix(button): withDefaults-修复button组件的默认props中type的值未填写

---

demo/components.d.ts
demo/vite.config.ts

fix(base): 修复windows路径转义错误导致无法导入

fix(base): 修复windows路径转义错误导致无法导入

---

.vscode/settings.json
CONTRIBUTING.md
config/script/new-component.mjs
demo/src/router/config/bar.json
demo/src/views/Modules.vue
demo/tsconfig.json
package.json

feat(base): 添加自动生成组件目录及路由脚本

---

demo/src/examples/back-top/back-top-primary.vue
demo/src/examples/back-top/doc.md
packages/yike-design-ui/src/components/back-top/src/back-top.ts
packages/yike-design-ui/src/components/back-top/src/back-top.vue
packages/yike-design-ui/src/utils/constant.ts
packages/yike-design-ui/src/utils/tools.ts

1. props 更名 `visibilityHeight` => `visibleHeight`  `type` => `theme`
2. props `visibleHeight & right & bottom` 支持传入 '20px' | '20' | 20
3. 增加 `behavior` props，可见 [MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollTo#%E5%8F%82%E6%95%B0)
4. `target` 不存在时抛出异常
5. 同步更改文档

refactor(back-top): enhance props & optimized code

---

config/script/preinstall.js
package.json

chore: only allow pnpm

---

demo/components.d.ts
packages/yike-design-ui/src/components/theme/src/theme.ts
packages/yike-design-ui/src/components/theme/src/theme.vue

refactor(theme): finish

---

.gitignore

fix(gitignore): ignore .history folder

---

config/script/new-component.mjs

```bash
pnpm run new tabs
```
It should be prompted:
```bash
[ERROR] 请输入正确的组件名称
[ERROR] 如：npm run new pagination 分页
[ERROR] 如：npm run new back-top 回到顶部
ELIFECYCLE  Command failed with exit code 233.
```
Current Tip:
```bash
[ERROR] 请输入正确的组件名称
ELIFECYCLE  Command failed with exit code 233.
```

fix(new-component): Incomplete tips

---

demo/src/examples/notification/doc.md
demo/src/examples/notification/notification-cb.vue
packages/yike-design-ui/src/components/notification/src/notification.vue

根据昨日DAFEI大佬的建议，今天已修改了部分功能点以及docs内容：
1. 参考element-plus官网，将提醒框默认duration修改为4500；
2. docs增加了关于回调函数操作的说明；
3. DAFEI大佬提到的handleOK回调失效问题，由于merge后被修改了代码，但漏改了一处，已修复；

feat(notificaiton): update the feature and the docs.

---

demo/src/examples/rate/doc.md
demo/src/examples/rate/rate-size.vue
packages/yike-design-ui/src/components/rate/src/rate.ts
packages/yike-design-ui/src/components/rate/src/rate.vue
packages/yike-design-ui/src/components/rate/style/index.less

1.新增 size 属性
2.整理className
3.整理style

feat(rate): add size prop

---

packages/yike-design-ui/src/components/button/src/button.vue
packages/yike-design-ui/src/utils/bem.ts

fix(bem):  fix multipart class

---

demo/src/router/index.ts

docs(router): add afterEach scrollTo

---

demo/src/examples/notification/doc.md
demo/src/examples/notification/notification-position.vue
packages/yike-design-ui/src/components/notification/src/notification-group.vue
packages/yike-design-ui/src/components/notification/src/notification.ts
packages/yike-design-ui/src/components/notification/src/notification.vue
packages/yike-design-ui/src/components/notification/src/utils.ts
packages/yike-design-ui/src/components/notification/style/index.less
packages/yike-design-ui/src/components/styles/animate.less

根据yike走查反馈，新增position属性，支持配置Notification出现位置

feat(notification): add position attr

---

packages/yike-design-ui/src/components/rate/style/index.less

fix(rate): fix readonly/disabled style

---

build/bin/index.js
build/package.json

#226 针对这个issue的问题分析和复现情况，提供了此PR的方案

fix(build): 修复@yike/build影响pnpm i执行问题

---

demo/src/examples/text-area/doc.md
demo/src/examples/text-area/text-area-auto.vue
demo/src/examples/text-area/text-area-limit.vue
demo/src/examples/text-area/text-area-primary.vue
demo/src/examples/text-area/text-area-status.vue
demo/src/router/config/bar.json
demo/src/router/modules/general.ts
packages/yike-design-ui/src/components/text-area/index.ts
packages/yike-design-ui/src/components/text-area/src/text-area.ts
packages/yike-design-ui/src/components/text-area/src/text-area.vue
packages/yike-design-ui/src/components/text-area/src/utils.ts
packages/yike-design-ui/src/components/text-area/style/index.less
packages/yike-design-ui/src/components/text-area/style/index.ts
packages/yike-design-ui/src/index.ts

feat(textarea): new component textarea

---

demo/src/examples/divider/divider-horizontal.vue
demo/src/examples/divider/divider-primary.vue
demo/src/examples/divider/divider-style.vue
demo/src/examples/divider/divider-vertical.vue
demo/src/examples/divider/doc.md
demo/src/router/config/bar.json
demo/src/router/modules/general.ts
packages/yike-design-ui/src/components/divider/index.ts
packages/yike-design-ui/src/components/divider/src/divider.ts
packages/yike-design-ui/src/components/divider/src/divider.vue
packages/yike-design-ui/src/components/divider/style/index.less
packages/yike-design-ui/src/components/divider/style/index.ts
packages/yike-design-ui/src/index.ts

feat(divider): add divider component

---

demo/src/examples/progress/progress-circle.vue
packages/yike-design-ui/src/components/progress/src/progress.vue
packages/yike-design-ui/src/components/progress/src/util.ts
packages/yike-design-ui/src/components/progress/style/index.css
packages/yike-design-ui/src/components/progress/style/index.less
packages/yike-design-ui/src/components/styles/theme.css
pnpm-lock.yaml

fix(progress): 进度条组件状态颜色问题修改

---

demo/src/examples/link/doc.md
demo/src/examples/link/link-primary.vue
demo/src/examples/link/link-typography.vue
demo/src/router/config/bar.json
demo/src/router/modules/general.ts
packages/yike-design-ui/src/components/link/index.ts
packages/yike-design-ui/src/components/link/src/link.ts
packages/yike-design-ui/src/components/link/src/link.vue
packages/yike-design-ui/src/components/link/style/index.less
packages/yike-design-ui/src/components/link/style/index.ts
packages/yike-design-ui/src/index.ts

feat(link): new component -- Link

---

packages/yike-design-ui/src/components/input-number/src/input-number.vue

fix(input-number): 处理getDisplayValue中字符串toFixed报错。

---

packages/yike-design-ui/src/components/pagination/src/components/pagination-jumper/pagination-jumper.vue

将 yk-input 替换为 yk-input-number，利用input-number的性质控制用户输入。

feat(pagination): 将 yk-input 替换为 yk-input-number，利用input-number的性质控制用户输入。

---

demo/src/views/HomeView.vue

fix(主页): 修复了主页底部出现水平滚动条问题

---

packages/yike-design-ui/src/components/input/src/input.vue
packages/yike-design-ui/src/components/pagination/src/pagination.vue

当分页组件输入的值比totalPages大的时候，保存最大值
fixes https://github.com/ecaps1038/yike-design-dev/issues/277

fix: pagination's input value greater than totalPages

---

demo/src/examples/popover/doc.md
demo/src/views/HomeView.vue

fix(ppopover文档): 修复文档链接跳转不正常问题]

修复文档链接跳转不正常问题

---

demo/src/components/Codes.vue
demo/src/components/DocPage.vue
demo/src/components/Snippet.vue
demo/src/style/main.less
demo/src/style/markdown.less

fix: optimize doc style

---

packages/yike-design-ui/src/components/calendar/src/utils.ts
packages/yike-design-ui/src/components/calendar/style/index.less

修复日历组件显示错位问题 fixes https://github.com/ecaps1038/yike-design-dev/issues/295

fix: Calendar font display missed

---

demo/src/components/NavBar.vue
demo/src/examples/typography/doc.md
demo/src/examples/typography/paragraph-ellipsis.vue
demo/src/examples/typography/paragraph-primary.vue
demo/src/examples/typography/text-type.vue
demo/src/style/markdown.less
packages/yike-design-ui/src/components/typography/src/paragraph.vue
packages/yike-design-ui/src/components/typography/src/text.vue
packages/yike-design-ui/src/components/typography/src/title.vue
packages/yike-design-ui/src/components/typography/src/typography.ts
packages/yike-design-ui/src/components/typography/style/index.less
packages/yike-design-ui/src/components/utils/constant.ts
packages/yike-design-ui/src/components/utils/tools.ts

* fix: remove useless code
* fix(paragraph): dynamic truncate text

refactor(typography): fix some bugs

---

demo/src/examples/typography/doc.md
demo/src/examples/typography/paragraph-ellipsis.vue
packages/yike-design-ui/src/components/typography/src/paragraph.vue
packages/yike-design-ui/src/components/typography/src/typography.ts
packages/yike-design-ui/src/components/typography/style/index.less

修复 paragraph 展开状态容器宽度变化时没有隐藏‘收起’按钮的 bug

feat(paragraph): add copyBefore hook

---

.github/workflows/gh-pages.yaml
demo/src/router/index.ts
demo/src/views/NotFound.vue

- use html5 mode router to fix #314 
- copy a 404.html file from index.html to avoid 404 in github pages, refer to [docs](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site)
- add a 404-not-found page

fix: routing related issues

---

packages/yike-design-demo/src/examples/pagination/pagination-primary.vue
packages/yike-design-ui/CHANGELOG.md
packages/yike-design-ui/components/modal/src/modal.vue
packages/yike-design-ui/components/pagination/src/components/pagination-pager/pagination-pager.vue
packages/yike-design-ui/package.json

* **modal:** should not trigger keydown event when modelValue is false ([73af440](https://github.com/ecaps1038/yike-design-dev/commit/73af440194f37d2c143aac8c1a1cc62808d06a8a))
* **pagination:** fix lost page 2 when total page is 3 ([e32feb6](https://github.com/ecaps1038/yike-design-dev/commit/e32feb6bac447fbf0c4fee4336aece6bd972f408))

Version 0.0.12

---

packages/yike-design-demo/src/components/Snippet.vue
packages/yike-design-ui/components/radio/src/radio-group.vue
packages/yike-design-ui/components/space/src/space.vue

* fix(space): fix space undifined
* fix radio-group dirction
* use other snippet icon class name

fix(space): fix space undifined

---

packages/yike-design-ui/components/input/src/input.vue
packages/yike-design-ui/components/input/style/functions.less
packages/yike-design-ui/components/input/style/index.less

fix(input): remove multiple bem

fix(input): remove multiple bem

---

packages/yike-design-ui/components/pagination/style/index.less

pagination的pager-item添加默认小指头的鼠标样式怎么样呀

给 pagination 组件的item添加默认鼠标样式
